# Generated by Django 5.2.17 on 2026-09-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawS3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500)),
                ('s3_bucket', models.CharField(max_length=500)),
                ('pathfilename', models.CharField(max_length=500)),
                ('rawjson', models.JSONField()),
            ],
        ),
    ]
