# Generated by Django 5.2.17 on 2026-10-03 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3_ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raws3',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
