# Generated by Django 5.2.17 on 2026-10-03 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3_ingestion', '0002_raws3_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raws3',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
